[Colors]
Text = 0xFFFFFFFF
Window = 0xFF343434
Background = 0xFF282828
SelectedOutline = 0xFF00a8ec
MenuFocused = 0xFFFFA000
MenuSelected = 0xFFFF0000
AutoCompleteSubText  = 0xB0B0B0
AutoCompleteDocText = 0xC0C0C0
AutoCompleteActiveText = 0xFF0000

Code = 0xFFB98AFF
Keyword = 0xFF569cd6
Literal = 0xFFd69D85
Identifier = 0xFFdcdcdc
Type = 0x4ec9b0
RefType = 0x4ec9b0
Interface = 0xC6E8B0
Comment = 0xFF80966C
Method = 0xFFDBDB95
Namespace = 0xFFAAAAAA
DisassemblyText = 0xFFB0B0B0
DisassemblyFileName = 0xFFFF0000

Error = 0xFFFF0000
BuildError = 0xFFFF8080
BuildWarning = 0xFFFFFF80
VisibleWhiteSpace = 0xFF9090C0
